### ISSUE TITLE
Typos in readme ?

### ISSUE THREAD

**Issue by stefkes** [binafy/laravel-cart#13]
In several places there's a mention of Laravel "Card", which is not the same as Cart. Is this a typo that needs to be fixed or does it refer to something else ? Quite confusing since of course cards are actually used for payments.

> Easily integrate credit card and payment processing functionality into your Laravel application with Laravel Card.

> Laravel Card is designed to be highly customizable

> Secure card information storage

**Comment by milwad-dev** [comment]
No today, I'm updating the readme and fixing all bugs and problems.

https://github.com/binafy/laravel-cart/pull/8
