### ISSUE TITLE
Adding item to cart should not create a new item, but increase quantity

### ISSUE THREAD

**Issue by UnrulyNatives** [binafy/laravel-cart#15]
In the code presented in `Store Items For a Cart` the logic simply adds a DB record in the table. 
This works well when adding a first itemable product. 

Should be: If a buyer press the same button again, the logic should increase quantity.
Now: A new entry in the CartItem model is created.

Also, an `inctrease quoantity` feature should be implemented.

**Comment by milwad-dev** [comment]
Yes, we add a new method in the `Laravel Cart` update.

**Comment by milwad-dev** [comment]
https://github.com/binafy/laravel-cart/pull/16
