### ISSUE TITLE
This may extend the project, creating integration with these packages

### ISSUE THREAD

**Issue by Wotan6891** [binafy/laravel-cart#24]
Hello,

This may extend the project, creating integration with these packages:

https://github.com/Saberqadimi/manage-payment-and-orders
https://github.com/Caryley/Laravel-Inventory
https://github.com/shetabit/payment

You could create notifications that are sent to email when someone makes a purchase or cancels the purchase:
https://laravel.com/docs/11.x/notifications

Greetings and thanks

**Comment by milwad-dev** [comment]
Hello, I'm happy to see this package is useful for you.

For send email or something else, you can listen to these events:

https://github.com/binafy/laravel-cart?tab=readme-ov-file#available-events
