### ISSUE TITLE
Session Driver Not Working

### ISSUE THREAD

**Issue by rayltcero** [binafy/laravel-cart#26]
I followed the [docs](https://github.com/binafy/laravel-cart/blob/1.x/README.md) to implement a session driver cart when users are not logged in, but I'm getting the following error message "Driver [session] not supported."

```
LaravelCart::driver('session')->storeItem([
    'itemable_id' => $this->product->id,
    'itemable_type' => Inventory::class,
    'quantity' => 1,
]);
```

![image](https://github.com/user-attachments/assets/ac3dd0d4-491f-46f4-a2c5-5f8f2bf06bfa)

**Comment by milwad-dev** [comment]
https://github.com/binafy/laravel-cart/releases/tag/v1.1.0
