### ISSUE TITLE
The carts and cart_items databases in the vendor are also migrated

### ISSUE THREAD

**Issue by wahyuachmad** [binafy/laravel-cart#28]
hello I have a problem when running the php artisan migrate command, the problem is in the form of files 2024_05_31_102710_create_carts_table.php and
2024_05_31_103315_create_cart_items_table.php in the vendor follow migrate.

So I need to add --path when migrating “php artisan migrate --path=database/migrations” so that the migrate target is only in “database\migrations”.

can you rename the file with a stub? 
2024_05_31_102710_create_carts_table.php.stub
2024_05_31_103315_create_cart_items_table.php.stub 
so when in the migration command, there is a copy of the file you just need to delete the .stub in the file name

then you also need to change the year month date in the file name with the latest date, for example I run the command “php artisan vendor:publish --tag=”laravel-cart-migrations“” on 12-12-2024 at 03:01:40 (HHMMSS)

then the latest file name that is copied is
2024_12_12_030140_create_carts_table.php
2024_12_12_030140_create_cart_items_table.php

Thank you, sorry if there are words that are missing ... because I use a translator

Translated with DeepL.com (free version)

![Screenshot 2024-12-12 023850](https://github.com/user-attachments/assets/7870df8b-c958-4bd4-b09c-e692f8c7f718)

**Comment by milwad-dev** [comment]
You need to publish the migrations:

https://github.com/binafy/laravel-cart?tab=readme-ov-file#publish

**Comment by milwad-dev** [comment]
Also, you can change the datetime of migrations.
