### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by sadekd** [binafy/laravel-cart#3]
Hello, I dont see these features(in the code), as its described in readme.

maybe its planned for future version, but now it can be misleading, remove it or mark as todo 😉

![Screenshot_20240627-225416](https://github.com/binafy/laravel-cart/assets/6051891/bd8da747-63ac-4726-8116-b0b6b4088867)

**Comment by milwad-dev** [comment]
We will add some features and create an amazing cart package for Laravel.
