### ISSUE TITLE
How to add Attributes and Options

### ISSUE THREAD

**Issue by MuhammadZaheerUdDin** [binafy/laravel-cart#30]
how to add attributes ,
Attributes and Options: Define custom attributes and options for cart items to handle variations like size and color.
as given doesn't support ,

stale branch exist which is also missing some new features (increment / decrement)
[feat/add-options](https://github.com/binafy/laravel-cart/tree/feat/add-options)

**Comment by milwad-dev** [comment]
This feature will be added soon.
